--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Heisenburger69/BurgerSpawners
build-by-default: true
branches:
- master
projects:
  BurgerSpawners:
    path: ""
    icon: Spawner_JE3.png
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^1.0.0
      - src: JackMD/ConfigUpdater/ConfigUpdater
        version: ^1.0.0
...
